export const MAX_MODEL_TITLE_LENGTH = 100
export const MAX_MODEL_DESCRIPTION_LENGTH = 1000
export const MAX_MODEL_PROMPT_LENGTH = 2000
export const MAX_MODEL_IMAGE_URL_LENGTH = 2048
export const MAX_MODEL_MATERIAL_LENGTH = 120
export const MAX_MODEL_COLOR_LENGTH = 60
export const MAX_MODEL_STYLE_LENGTH = 120
export const MAX_MODEL_FILENAME_LENGTH = 120
export const MIN_MODEL_DIMENSION = 0.1
export const MAX_MODEL_DIMENSION = 1000
export const MAX_MODEL_IMAGE_FILE_SIZE = 5 * 1024 * 1024 // 5MB

export const MAX_EMAIL_LENGTH = 254
export const MAX_PASSWORD_LENGTH = 128
export const MAX_ADMIN_NAME_LENGTH = 80
