name: app

on:
  push:
    branches:
      - develop
  # schedule:
  #   - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Configure npm (retries, registry)
        run: |
          npm config set fetch-retries 5
          npm config set fetch-retry-maxtimeout 600000
          npm config set fetch-retry-mintimeout 20000
          npm config set registry ${NPM_REGISTRY_URL:-https://registry.npmjs.org/}
        env:
          NPM_REGISTRY_URL: ${{ secrets.NPM_REGISTRY_URL }}

      - name: Install dependencies (retry)
        run: |
          for i in 1 2 3; do
            npm ci --no-audit --no-fund && break || sleep $((i*10));
          done
      - run: npx prisma generate
      - run: npm run lint
      - run: npm run test:coverage
      - run: npm run build

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage
          retention-days: 30
          if-no-files-found: ignore

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: build
      #     path: .next
      #     include-hidden-files: true
      #     retention-days: 30
      #     if-no-files-found: error
