name: app

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npm ci
      - run: npx prisma generate
      - run: npm run lint
      - run: npm run test:coverage
      - run: npm run build

      - name: Debug artifact upload issue
        run: |
          echo "=== Working directory ==="
          pwd
          echo "=== .next directory details ==="
          ls -la .next/
          echo "=== .next directory size ==="
          du -sh .next/
          echo "=== Test glob pattern ==="
          ls -la .next* || echo "no .next* files"
          echo "=== File count in .next ==="
          find .next -type f | wc -l
          echo "=== Upload artifact version ==="
          echo "Using upload-artifact@v4"

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 30
          if-no-files-found: ignore

      # Test multiple v4 approaches
      - uses: actions/upload-artifact@v4
        with:
          name: build-approach1
          path: ".next"
          retention-days: 30
          if-no-files-found: warn

      - uses: actions/upload-artifact@v4
        with:
          name: build-approach2
          path: ".next/"
          retention-days: 30
          if-no-files-found: warn

      - uses: actions/upload-artifact@v4
        with:
          name: build-approach3
          path: |
            .next
          retention-days: 30
          if-no-files-found: warn

      - uses: actions/upload-artifact@v4
        with:
          name: package-files
          path: |
            package.json
            package-lock.json
            next.config.js
          retention-days: 30
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        with:
          name: static-assets
          path: public
          retention-days: 30
          if-no-files-found: ignore
